name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          go mod download
          go build -o merch_app .

    #   - name: Upload merch_app artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: merch_app_artifact
    #       path: merch_app

  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: | 
          go test -v

    #   - name: get merch_app_artifact
    #     uses: actions/download-artifact@v4
    #     with: 
    #         name: merch_app_artifact

  docker_compose:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker compose
        run: docker compose up --build