name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          go mod download
          go build -o merch_app .

  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v4


      - name: test
        run: | 
          ./merch_app & go test -v
